exports.Labels = {
    "Empty":"Empty",
    "Yes":"Yes",
    "No":"No",
    "PleaseWait":"Please Wait",
    "Apply":"Apply",
    "Cancel":"Cancel",
    "Submit":"Submit",
    "Accept":"Accept",
    "Close":"Close",
    "Done":"Done",
    "Next":"Next",
    "Save":"Save",
    "Logout":"Logout",
    "Login":"Login",
    "Exit":"Exit",
    "Admin":"Admin",
    "Dashboard":"Dashboard",
    "Control Panel":"Control Panel",
    "Account":"Account",
    "Home":"Home",
    "Form":"Form",
    "Default" : "Default",
    "Online" : "Online",
    "Offline" : "Offline",
    "Install" : "Install",
    "Installed" : "Installed",
    "Reinstall" : "Reinstall",
    "NotInstalled" : "Not installed",
    "Suspended" : "Suspended",
    "Active" : "Active",
    "Status" : "Status",
    "RunningOn" : "Running on",
    "Granted" : "Granted",
    "Denied" : "Denied",

    "serverManagement":"Server Management",
    "help":"Help",
    "logout":"Logout",
    "logoutQuestion":"Do you really want to log out?",
    "fileManager":"File Manager",
    "codeEditor":"Code Editor",
    "serviceManagement":"Service Management",
    "stats":"Server Stats",
    "UsersUpperCase":"Users",
    "users":"users",

    "RefreshTooltip":"Refresh selected folder",
    "AddTooltip":"Add a new file or folder",
    "DeleteTooltip":"Delete selected file or folder",
    "RenameTooltip":"Rename selected file or folder",
    "DownloadTooltip":"Download file or folder",
    "UploadTooltip":"Upload a file to server",
    "UploadCompleted":'Upload is completed.',
    "UploadFailed":"Upload operation is failed. Try again.",

    "Refresh":"Refresh",
    "Add":"Add",
    "Delete":"Delete",
    "Rename":"Rename",
    "Download":"Download",
    "Upload":"Upload",

    "MessageSuccess" : "Success",
    "MessageInfo" : "Info",
    "MessageDanger" : "Something went wrong...",
    "MessageError" : "Something went wrong...",
    "MessageWarning" : "Warning!",

    "MSBrowserOutOfDate": "Your browser is out of date, please update your browser by going to www.microsoft.com/download",
    "SessionExpired": "The user session is expired. Please login again!",
    "CannotLoginNoUser" : "Cannot login. User does not exists in database.",
    "CannotLoginNoAccess" : "Cannot login to JXPanel (access denied).",
    "CouldntFixFolderPermissions":"There was a problem with folder permissions during user creation",

    "Access Denied": "You do not have a permission to view this resource.",
    "CallbackRequired" : "The callback is required.",

    //Form
    "Nothing to Apply": "There was nothing to apply. Operation wasn't successful.",
    "UnknownForm" : "Unknown form",
    "FormEmpty" : "The form does not contain any controls.",
    "FormError" : "Some field values are invalid. Please enter correct values.",

    // Form names
    "addUser" : "Add new user",
    "addSubscription" : "Add new subscription",
    "addPlan": "Add new hosting plan",
    "addDomain": "Add new domain",
    "appLog": "Application log",

    // login page
    "SignIn" : "Sign In",
    "StaySignedIn" : "Stay signed in",
    "Username" : "System user name",
    "UsernameEnter" : "Please enter your username",
    "UsernameEnterRequired" : "Please enter valid username",

    "Password" : "Password",
    "PasswordForgot" : "Forgot password?",
    "PasswordConfirm" : "Confirm password",
    "PasswordRepeat" : "Repeat password",
    "PasswordEnter" : "Enter your password",
    "PasswordEnterRequired" : "Please enter your password",
    "PasswordDoesNotMatch" : "Password does not match",

    "DataPlans": "Hosting Plans",
    "DataPlansHeader": "Customize the options",
    "DataPlansContent": "Fill the below inputs to define a hosting plan. You can use a hosting plan for multiple users.",
    "DataPlansHeaderList": "Customize the hosting plans",
    "DataPlansContentList": "Hosting plans are set of rules which define hosting options and limits. You can use a hosting plan for multiple users.",

    "CredentialsFailed": "Incorrect username and/or password",
    "WelcomeDashboard": "Welcome %s!",

    "BlockLeftHeader" : "About SmartAdmin - Are you up to date?",
    "BlockLeftBody" : "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.",
    "BlockRightHeader" : "Not just your average template!",
    "BlockRightBody" : "Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi voluptatem accusantium!",

    // form controls
    "ComboNotSelected" : "not selected",
    "UserContactName" : "Contact Name",
    "UserEmailAddress" : "Email Address",
    "UserSubscriptionAccess" : "Access to subscriptions",
    "UserPanelLanguage" : "JXPanel language",
    "UserFTPAccess" : "FTP access",
    "UserPanelAccess" : "JXPanel access",

    "ValueRequired" : "This field is required.",
    "ValueInvalid" : "The value for the field is invalid.",
    "ValueInvalidBoolean" : "The value is supposed to be boolean.",
    "ValueInvalidInteger" : "The value is supposed to be integer.",
    "ValueInvalidIntegerOf" : "The value of %s is supposed to be integer.",
    "ValueNotDefined" : "not defined",
    "ValueUnlimited" : "unlimited",

    "RequiresMinimumLength": "Minimum string length for this control must be %s.",
    "RequiresMaximumLength": "Maximum string length for this control must be %s.",

    "ValueShouldBe": "The value should be %s.",
    "less than" : "less than",
    "greater than" : "greater than",
    "equal" : "equal",
    "and" : "and",
    "or" : "or",

    // Pages
    "Subscription" : "Subscription Management",

    "UsersManagement" : "User Management",
    "UsersHeader": "Customize the options",
    "UsersContent": "Create new users and manage their options.",
    "UsersHeaderList": "Customize the options",
    "UsersContentList": "Create new users and manage their options.",

    "UsersCannotCreateSystemUser" : "Cannot create system user.",
    "UsersCannotUpdatePassword" : "Cannot update system user's password.",
    "UsersCannotDeleteSystemUser" : "Cannot delete system user.",
    "UsersCannotDeleteSystemUsersFolder" : "Cannot delete user's folder.",

    "domains" : "domains",
    "DomainsUpperCase" : "Domains",
    "DomainsManagement" : "Domain Management",
    "DomainsHeader": "Customize the options",
    "DomainsContent": "Create new domains and manage their options.",
    "DomainsHeaderList": "Customize the options",
    "DomainsContentList": "Create new domains and manage their options.",


    "CodeEditor":"Code Editor",
    "CodeEditorTop": "Select source file(s) from below to view and edit on the editor.",
    "SystemInfo": "System Information",
    "UnableToRead": "Unable to read this information",
    "OSname": "OS",
    "Loading": "Loading...",
    "FileNotFound": "File not found",
    "FileTypeNotSupportedTitle":"Not Supported",
    "FileTypeNotSupportedContent":"Editing this file type is not supported.",
    "FileSavedTitle":"Done!",
    "FileSavedContent":"File Saved Successfully",
    "FolderNotEmpty":"Folder is not empty",
    "FileExists":"File already exists",
    "FileDoesNotExist":"File does not exist",
    "PathCannotContain" : "The path cannot contain the following: `%s`.",
    "PathCannotStart" : "The path cannot start with the following: `%s`.",
    "CHMOD":"chmod",
    "CHMODTooltip":"Update CHMOD",
    "SelectFolder":"Select a folder to add file",
    "CreateNewFileFolder":"Create new",
    "Location":"Location",
    "File":"File",
    "Folder":"Folder",
    "NameForTheFile":"Name for the",
    "MustDefineFileFolderName":"You should define a name",
    "FileCreated":"Created",
    "SelectFileFolder":"Select a folder or a file",
    "DeletingFileFolder":"Deleting",
    "AreYouSure":"Are you sure ?",
    "FileFolderDeleted":"Successfully Deleted",
    "FileFolderRenaming":"Renaming",
    "EnterNewFileFolderName":"Enter a new name",
    "NoSpecialCharsFileFolderName":"Name can not contain special characters!",
    "EnteredSameFileFolderName":"You have entered the same name!",
    "FileFolderRenamed":"Successfully Renamed",
    "SelectFolder":"Select a folder to refresh",
    "SelectFileFolderDownload":"Select a folder or a file to download",
    "CantDownloadRoot":"You can not download the root folder",
    "LinkToDownload":"Use below one-time link to download..",
    "Download":"Download",
    "Upload":"Upload",
    "SelectFileFolderUpload":"Select a folder for upload location",
    "SelectFileToUpload":"Select a file to upload..",
    "SelectFileFolderCHMOD":"Select a folder or a file to update chmod",
    "CantCHMODRoot":"You can not change the root folder",
    "CHMODUpdating":"Updating",
    "DIDNTChangeCHMOD":"You didn't change the file mode",
    "CHMODSpecialChars":"File Mode needs to be a three digit number (0-7)",
    "CHMODisDone":"File mode updated successfully",

    // user form
    "UserAlreadyExists" : "User with this name already exists.",
    "UserSystemAlreadyExists" : "System user with this name already exists.",
    "UserUnknown" : "Unknown user.",
    "UserHomeDirNotExists" : "User's home directory does not exists.",
    "EmailInvalid" : "Invalid e-mail address.",


    // Terminal
    "RemoteManagement":"Remote Management",
    "SSHNotAllowed":"Remote management access is disabled for this user account",
    "Restart":"Restart",
    "RestartTerminalTooltip":"Restart Terminal Instance",
    "StopOperation":"Stop Operation",
    "StopOperationTooltip":"Stop Active Operation",
    "TerminalConnectedToServer":"Terminal Client is Connected",
    "TerminalConnectingToServer":"Connecting to Server...",
    "TerminalTop": "Below window represents an interface to server's bash",
    "TerminalStopWarning":"Detached sub processes created by terminal instance may stay alive",
    "TerminalStopMessage1":"Canceling the Operation..",
    "TerminalStopMessage2":"Terminal Tasks are Cancelled",
    "RestartingTerminal": "Restarting Terminal",
    "TerminalPleaseWait": "Please wait. Operating...",

    "ServerNotResponding": "Server is not responding",
    "ReloginQuestion": "Would you like to re-login ?",
    "YouHaveBeenAway": "You've been away",

    // Plan
    "plans":"plans",
    "PlanName" : "Plan name",
    "PlanID" : "Hosting Plan",
    "Overuse" : "Allow overuse",
    "MaxDiskSpace" : "Disk space",
    "MaxDiskSpace_Description" : "Maximum disk usage (MB). Empty value disables the limit.",
    "MaxTraffic" : "Traffic",
    "MaxTraffic_Description" : "Maximum amount of transferred data during given period of time. Empty value disables the limit.",
    "MaxCPU" : "Max CPU",
    "MaxCPU_Description" : "Maximum CPU usage (percentage) allowed for the application. Empty value disables the limit.",
    "MaxCPUInterval" : "CPU check interval",
    "MaxCPUInterval_Description" : "Interval (seconds) of Max CPU usage check. Default value is 2.",
    "MaxMemory" : "Max memory limit",
    "MaxMemory_Description" : "Maximum size of memory (kB), which can be allocated by the application. Empty value disables the limit.",
    "MaxDomains" : "Max domains",
    "MaxDomains_Description" : "Maximum amount of domains. Value 0 disables adding new domains.",
    "AllowSSL" : "Allow secured SSL port",
    "AllowCustomSocketPort" : "Allow custom socket port",
    "AllowSysExec" : "Allow to spawn/exec child processes",
    "AllowLocalNativeModules" : "Allow to call local native modules",
    "AppLogWebAccess" : "Application`s log web access",
    "AppLogWebAccess_Description" : "Will be available on http://yourdomain.com/jxcore_logs/index.txt",
    "AllowSSH" : "SSH",
    "NginxDirectives" : "NGINX directives",
    "MaxUsers" : "Max users",
    "MaxUsers_Description" : "Maximum amount of users. Value 0 disables adding new users.",
    "MaxPlans" : "Max plans",
    "MaxPlans_Description" : "Maximum amount of hosting plans. Empty value disables the limit. Value 0 disables adding new plans.",

    "DomainName" : "Domain",
    "DomainName_Description" : "The domain name for you subscription.",
    "DomainInvalid" : "Please enter a valid domain name.",
    "DomainAlreadyExists" : "Domain already exists.",
    "DomainNotFound" : "Domain not found.",
    "DomainCannotAdd" : "Cannot add domain.",
    "DomainCannotRemoveDir" : "Cannot remove domain's directory.",
    "DomainHomeDirDoesNotExist" : "Domain's home directory does not exist.",

    "IPv4" : "IPv4 address",
    "IPv6" : "IPv6 address",
    "JXEnabled" : "JXcore",
    "JXcoreAppPath" : "Application file path",
    "JXcoreAppStatus" : "Application status",
    "JXcoreAppPath_Description" : "The path is relative to domain root folder.",

    // JXcore
    "JXcoreUpperCase" : "JXcore",


    "NoPlan" : "You have no hosting plan assigned. Please contact an administrator.",
    "NoPlanOwned" : "You have no hosting plan of your own. Please add one.",
    "PlanCannotAddUsers" : "This hosting plan does not allow to add any users.",
    "PlanCannotAddMoreUsers" : "This hosting plan does not allow to add more than %s users.",
    "PlanCannotAddDomains" : "This hosting plan does not allow to add any domains.",
    "PlanCannotAddMoreDomains" : "This hosting plan does not allow to add more than %s domains.",
    "PlanCannotAddPlans" : "This hosting plan does not allow to add any other hosting plans.",
    "PlanCannotAddMorePlans" : "This hosting plan does not allow to add more than %s hosting plans.",
    "PlanCannotDetermineHostingValues" : "Cannot determine hosting values.",
    "PlanParentCannotAddMore" : "Parent hosting plan reached maximum %s count.",
    "PlanCannotAddMore" : "This hosting plan reached maximum %s count (%s).",
    "PlanInvalid" : "Invalid hosting plan",
    "PlanAlreadyExists" : "Plan already exists",
    "PlanParentDefinesValue" : "Parent hosting plan defines this value as %s.",
    "UserSuspended" : "User is suspended",
    "PlanSuspended" : "Hosting plan is suspended",
    "YouAreSuspended" : "You are suspended (%s).",
    "YouAreSuspendedExtra" : "You can only edit and remove records. Adding records or launching applications is disabled.",

    "CannotEditRecord" : "You cannot edit this record.",


    "testForm": "Test Form",


    // DB
    "DBNotOpened" : "Database is not opened.",
    "DBCannotAddUser" : "Cannot add user to database.",
    "DBCannotGetUser" : "Cannot read user data from database.",
    "DBCannotGetParentUser" : "Cannot read parent user data from database.",
    "DBCannotGetPlan" : "Cannot read hosting plan from database.",
    "DBCannotGetParentPlan" : "Cannot read parent hosting plan from database.",
    "DBCannotGetDomain" : "Cannot read domain from database.",
    "DBCannotReadData" : "Cannot read data from database.",

    "DBUserCannotCreatePlan" : "User cannot create plan.",
    "DBCannotRemoveRecord" : "Cannot remove record %s.",

    "AccessDeniedToRemoveRecord" : "You have no privileges to delete the following %s: %s",
    "AccessDeniedToEditRecord" : "You have no privileges to edit the following %s: %s",

    // datatables
    "UnknownDataTable" : "Unknown table name.",
    "EmptySelection" : "Select the rows first.",
    "RemoveSelected" : "Remove selected",
    "RemoveSelectedHeader" : "Warning!",
    "RemoveSelectedQuestion" : "Are you sure to remove selected records?",
    "RemoveSelectedInfo" : "This operation cannot be undone.",

    "RemoveSelectedDomainsQuestion" : "Are you sure to remove selected domains?",
    "RemoveSelectedDomainInfo" : "Would you like to delete also files and folders including user's files?",
    "RemoveWithUserFiles" : "Remove also user files",
    "RemoveWithoutUserFiles" : "Remove only records, leave user files intact",

    //charts
    "DiskUsageInformation": "Disk Usage",
    "ChartsTopCPUInfo": "Process CPU",
    "ChartsTopMemoryInfo": "Process Memory",
    "Capacity": "Capacity",

    // html
    "NoDiv" : "Could not find proper html object.",
    "NoTemplate" : "Could not find template for the %s.",

    "JXcoreUpperCase" : "JXcore",
    "JXcoreManagement" : "JXcore Management",
    "JXcoreHeader": "Customize the options",

    "JXcoreConfiguration" : "Configuration",
    "JXcoreInfo" : " Information",
    "JXcoreVersion" : " JXcore version",
    "JXcorePath" : " JXcore path",
    "JXcorePathInvalid" : "JXcore path does not exist.",
    "JXcoreMonitor" : "JXcore Monitor",
    "JXcoreMonitorStatus" : "Status ",
    "JXcoreMonitorAllowMonitorAPI" : "Allow monitoring API",
    "JXcoreMonitorAllowMonitorAPI_Description" : "Enables/disables application's access to `jxcore.monitor` module.",
    "JXcoreMonitorStatusStop_Description" : "If you stop, all the monitored applications will be terminated!",
    "JXcoreMonitorStatusStart_Description" : "If you start, all the JXcore enabled applications will be launched.",
    "JXcoreMonitorCannotStart" : "Cannot start JXcore monitor.",
    "JXcoreMonitorCannotStop" : "Cannot stop JXcore monitor.",
    "JXcoreMonitorStarted" : "JXcore monitor started.",
    "JXcoreMonitorStopped" : "JXcore monitor stopped.",
    "JXcoreMonitorNotRunning" : "JXcore monitor is not running.",
    "JXcoreMonitorStarting" : "Starting JXcore monitor",
    "JXcoreMonitorStopping" : "Stopping JXcore monitor",

    "JXcorePleaseInstall" : "Please install JXcore.",
    "JXcoreCannotDownload" : "Cannot download JXcore.",
    "JXcoreDownloading" : "Downloading JXcore",
    "JXcoreReinstall_Description" : 'If you reinstall JXcore, all the running node applications will be restarted after updating JXcore binary.',
    "JXcoreAppMinPort" : "Minimum app port number",
    "JXcoreAppMaxPort" : "Maximum app port number",
    "JXcoreAppMaxPort_Description" : "The port range should be greater than domain count multiplied by two (HTTP + HTTPS). It means, that you need two ports for each of your domains.",
    "JXcoreAppSmallPortRange" : "Too small port range. You need at least %s ports (instead of %s).",
    "JXcoreAppsRestartWarning" : "Submitting the form may result in restarting the monitor together with all running applications.",
    "JXcoreAppCannotStart" : "Cannot start application %s.",
    "JXcoreAppCannotStop" : "Cannot stop application %s.",
    "JXcoreAppStarted" : "Application %s started.",
    "JXcoreAppStopped" : "Application %s stopped.",
    "JXcoreAppStarting" : "Launching the application",
    "JXcoreAppsStarting" : "Launching user applications",
    "JXcoreAppStopping" : "Stopping the application",
    "JXcoreAppLog" : "Log file",
    "JXcoreAppViewLog" : "View the log file",
    "JXcoreAppLogSize" : "Log file size",
    "JXcoreAppLogCannotRead" : "Cannot read log file.",
    "JXcoreAppLogClear" : "Clear log",
    "JXcoreAppLogLines" : "Show last # lines",
    "JXcoreAppLogLines_Description" : "Displays only last # lines of the log file. Enter empty value to display the whole log.",



    "JXcoreNPMModules" : "NPM Modules",
    "JXcoreNPMAddModule" : "Install new module",
    "JXcoreNPMEnterName" : "Please enter a name for NPM module.",
    "JXcoreNPMCouldNotInstall" : "Could not install NPM module.",
    "JXcoreNPMCouldNotUnInstall" : "Could not uninstall the following NPM modules: %s.",
    "JXcoreNPMInstalled" : "NPM module successfully installed.",
    "JXcoreNPMInstalling" : "Installing NPM module",

    // Nginx
    "NginxConfDirCannotCreate" : "Cannot create Nginx config directory",
    "NginxDirectivesInvalid" : "Provided directives failed on test."
};


//{{label.LABELHERE}}